### ISSUE TITLE
suggestion: i18n 

### ISSUE THREAD

**Issue by Cyberhan123** [esbuild/esbuild.github.io#19]
I‘d like’to do the part of translation into Chinese

**Comment by watonyweng** [comment]
[esbuild-docs-cn](https://github.com/docschina/esbuild-docs-cn)

**Comment by watonyweng** [comment]
Contributions are welcome, and click [here](https://github.com/docschina/esbuild-docs-cn).

**Comment by Cyberhan123** [comment]
> Contributions are welcome, and click [here](https://github.com/docschina/esbuild-docs-cn).

ok
