### ISSUE TITLE
Single page

### ISSUE THREAD

**Issue by adamburgess** [esbuild/esbuild.github.io#21]
Would you consider a PR to make this website one single page?

Similar to https://mpv.io/manual/master/ or https://rollupjs.org/guide/en/

pro:
* can ctrl-f to find anything (oh this is so so nice)

con:
* larger download, slower page

**Comment by evanw** [comment]
No, I don't think so. I considered doing what Rollup does but I think the current setup is better. The documentation for the API is mostly one page exactly for this reason: https://esbuild.github.io/api/. But I think it makes more sense for the non-API pages to be separated out, so I'm going to keep it the way it is.
