### ISSUE TITLE
Bundling esbuild with esbuild (deno)

### ISSUE THREAD

**Issue by danielr1996** [esbuild/esbuild.github.io#32]
I'm trying to bundle a cli application with esbuild that uses esbuild internally to dynamically load modules. Now when i `deno run` the bundle the cli prints 
```
Usage:
  esbuild [options] [entry points]

Documentation:
  https://esbuild.github.io/

Repository:
  https://github.com/evanw/esbuild
....
```

Which seems to be the same as when running esbuild itself in cli mode, could there be a scoping problem when bundling files with esbuild that themself consume esbuild as a library? Not however that bundling the same file with `deno bundle` or running the unbundled file with `deno run` executes my cli and works as expected.

**Comment by evanw** [comment]
Sorry, this isn't the right repo. This is the repo for esbuild's documentation. The correct repo is here: https://github.com/evanw/esbuild/. Please repost this issue over there and provide a way to reproduce the issue.
